# Railway.toml
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[phases.setup]
commands = ["pip install -r requirements.txt"]

[phases.deploy]
startCommand = "python main.py"

[[deploy]]
instances = 1
strategy = "rolling"
